name: CI • Windows (x64, MSVC)

on:
  push:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v6

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - name: Setup MSVC Developer Command Prompt
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install dependencies
        run: shards install

      - name: Build App
        run: |
          shards build --release --no-debug --static

      - name: Testing App
        run: bin/greetings version

      - name: Crear el artifact
        uses: actions/upload-artifact@v7
        with: 
          name: greetings-windows-x64
          path: bin/greetings.exe
          retention-days: 2


